import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "@workspace/ui/globals.css";

const manRope = Manrope({
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${manRope.className} antialiased dark overflow-x-hidden max-w-screen h-full`}>
        {children}
      </body>
    </html>
  );
}
