-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "institution" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Experience" ALTER COLUMN "company" SET DATA TYPE TEXT,
ALTER COLUMN "role" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "username" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "firstname" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "lastname" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(100);
